#!/bin/sh 
# ipv6 toggle alias

if [ $# -eq 0 ]; then echo "ipv6 [on, off]" ; fi

case "$1" in
on)
sudo sysctl -w net.ipv6.conf.all.disable_ipv6=0
sudo sysctl -w net.ipv6.conf.default.disable_ipv6=0
;;
off)
sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1
sudo sysctl -w net.ipv6.conf.default.disable_ipv6=1
;; 
esac