#!/bin/sh
# opens files

	case $1 in 
		*.avi|*.png|*.gif|*.mp3|*.jpe|*.jpeg|*.jpg|*.mp4|*.mkv|*.mkv|*.mov|*.webm)
		$media "$1" ;;
		*.pdf)
		if command -v mupdf >/dev/null ; then mupdf "$1" 
        else $browser "$1" ; fi ;;
		*.sh|*.c|*.php|*.css|*.html|*.json|*)
        $editor "$1" ;;
    esac