#!/bin/sh
# temp ported to using dmenu,

choosen=$(printf "php\nc\nsh\npy\ndesktop\nmakefile\nhtml\n" | dmenu -p " Template menu: ")
cb() {
if command -v xclip >/dev/null ; then xclip -selection clipboard ; fi
}
if [ -z $choosen ]; then exit 1; fi

case "$choosen" in
html)
echo '<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1.0">
<title>text</title>
</head>
    <body>
        Hello World!
    </body>
</html>' | cb ;;
c) 
echo '#include <stdio.h>

int main() {
    printf("%s\n", "text");
    return 0;
}' | cb ;;
sh)
echo '#!/bin/sh

if [ $# -eq 0 ]; then echo "index []" ; fi' | cb ;;
py)
echo '#!/usr/bin/env python3

def main():
    print("hi")
if __name__ == "__main__":
    main()' | cb ;;
php)
echo '<?php

$greeter = "Hello world" ;
echo $greeter

?>' | cb ;;
desktop)
echo '[Desktop Entry]
Name=Hello World
GenericName=Hello-World
X-GNOME-FullName=Hello-World
Comment=Hello World
Keywords=World;
Exec=/usr/local/bin/index %u
Terminal=false
Type=Application
Categories=Utility;GNOME;Qt' | cb ;;
makefile)
echo 'PREFIX = /usr/local
path = ${DESTDIR}${PREFIX}/bin

all:
	@echo "Use make install."
install:
	install -Dm0755 index ${path}/index
uninstall:
	rm -rf -- ${path}/index
test:
	shellcheck index' | cb ;;
esac
