#!/bin/sh
vol=$(pamixer --get-volume)
# why doesn't this have a fucking LIMIT...
limit() {
if [ $vol -ge "100" ]; then
    pamixer --set-volume 100
fi   
}

if [ $vol = 0 ]; then volume='muted'
elif [ $vol -ge 0 ]; then volume=$vol%
fi

case "$1" in
m)
pamixer -t ;;
i)
pamixer -i 10 | limit ;;
d)
pamixer -d 10 ;;
s)
echo " $volume"
;;
esac
